apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deploy-staging.yaml
  - path: svc-staging.yaml
  - path: ingress-staging.yaml

namespace: app-staging

configMapGenerator:
  - name: app-config
    literals:
      - ENV=staging
      - LOG_LEVEL=info

images:
  - name: aphraz/node-app
    newTag: "1.1.1-staging"  # Ensures the latest staging image is used
