apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-dev  # Explicit namespace definition

resources:
  - ../../base

patchesStrategicMerge:
  - deploy-dev.yaml
  - svc-dev.yaml
  - ingress-dev.yaml

commonLabels:
  environment: dev
  app: my-node-app
